package GUI.updateDialog;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import GUI.insertDialog.*;
import data.DataManager;
import dataLogic.OperationManager;

/**
 *
 * @author Malbac
 */
public class ZmenaMajitela extends javax.swing.JPanel {

    /**
     * Creates new form VlozVlastnika
     */
    OperationManager operationManager;
    public ZmenaMajitela(DataManager dataManager) {
        operationManager = new OperationManager(dataManager);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonZmen = new javax.swing.JButton();
        LabelRodneCislo = new javax.swing.JLabel();
        TFRodneCisloStaryMajitel = new javax.swing.JTextField();
        labelState = new javax.swing.JLabel();
        labelSupisneCislo = new javax.swing.JLabel();
        TFsupisneCislo = new javax.swing.JTextField();
        LabelNazovKatastralnehoUzemia = new javax.swing.JLabel();
        TFNazovKatastralnehoUzemia = new javax.swing.JTextField();
        labelRemve = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LabelRodneCislo1 = new javax.swing.JLabel();
        TFRodneCisloNovyMajitel = new javax.swing.JTextField();

        buttonZmen.setText("Zmen");
        buttonZmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZmenActionPerformed(evt);
            }
        });

        LabelRodneCislo.setLabelFor(TFRodneCisloStaryMajitel);
        LabelRodneCislo.setText("rodne cislo stareho majitela");

        TFRodneCisloStaryMajitel.setText("rodne cislo");
        TFRodneCisloStaryMajitel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFRodneCisloStaryMajitelActionPerformed(evt);
            }
        });

        labelState.setText("XXXX");

        labelSupisneCislo.setText("supisne cislo");

        TFsupisneCislo.setText("supisne cislo");
        TFsupisneCislo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFsupisneCisloActionPerformed(evt);
            }
        });

        LabelNazovKatastralnehoUzemia.setText("nazov katastralneho uzemia");

        TFNazovKatastralnehoUzemia.setText("Nazov Katastralneh oUzemia");
        TFNazovKatastralnehoUzemia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNazovKatastralnehoUzemiaActionPerformed(evt);
            }
        });

        labelRemve.setText("Zmena majitela nehnutelnosti v zadanom kat. uzemi");

        LabelRodneCislo1.setLabelFor(TFRodneCisloStaryMajitel);
        LabelRodneCislo1.setText("rodne cislo noveho majitela");

        TFRodneCisloNovyMajitel.setText("rodne cislo");
        TFRodneCisloNovyMajitel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFRodneCisloNovyMajitelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonZmen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNazovKatastralnehoUzemia)
                            .addComponent(labelSupisneCislo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFNazovKatastralnehoUzemia, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(TFsupisneCislo)))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelRemve)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelRodneCislo1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelRodneCislo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(45, 45, 45)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFRodneCisloStaryMajitel, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(TFRodneCisloNovyMajitel))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(labelRemve)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFsupisneCislo)
                    .addComponent(labelSupisneCislo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFNazovKatastralnehoUzemia)
                    .addComponent(LabelNazovKatastralnehoUzemia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFRodneCisloStaryMajitel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelRodneCislo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRodneCislo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFRodneCisloNovyMajitel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(buttonZmen)
                .addGap(18, 18, 18)
                .addComponent(labelState)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TFRodneCisloStaryMajitelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFRodneCisloStaryMajitelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFRodneCisloStaryMajitelActionPerformed

    private void buttonZmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZmenActionPerformed
        String rodneCisloStaryMajitel = TFRodneCisloStaryMajitel.getText();
        String rodneCisloNovyMajitel = TFRodneCisloNovyMajitel.getText();
        String nazovKatastralnehoUzemia = TFNazovKatastralnehoUzemia.getText();
        int idSupisneCislo = Integer.parseInt(TFsupisneCislo.getText());

        String result= "";
        result = operationManager.getOperation11().zmenaMajitelaNehnutelnosti(rodneCisloStaryMajitel,rodneCisloNovyMajitel,idSupisneCislo,nazovKatastralnehoUzemia);
        labelState.setText(result);
    }//GEN-LAST:event_buttonZmenActionPerformed

    private void TFsupisneCisloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFsupisneCisloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFsupisneCisloActionPerformed

    private void TFNazovKatastralnehoUzemiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNazovKatastralnehoUzemiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNazovKatastralnehoUzemiaActionPerformed

    private void TFRodneCisloNovyMajitelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFRodneCisloNovyMajitelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFRodneCisloNovyMajitelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNazovKatastralnehoUzemia;
    private javax.swing.JLabel LabelRodneCislo;
    private javax.swing.JLabel LabelRodneCislo1;
    private javax.swing.JTextField TFNazovKatastralnehoUzemia;
    private javax.swing.JTextField TFRodneCisloNovyMajitel;
    private javax.swing.JTextField TFRodneCisloStaryMajitel;
    private javax.swing.JTextField TFsupisneCislo;
    private javax.swing.JButton buttonZmen;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelRemve;
    private javax.swing.JLabel labelState;
    private javax.swing.JLabel labelSupisneCislo;
    // End of variables declaration//GEN-END:variables
}
