package GUI.updateDialog;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import GUI.insertDialog.*;
import dataLogic.OperationManager;

/**
 *
 * @author Malbac
 */
public class ZmenaMajitela extends javax.swing.JPanel {

    /**
     * Creates new form VlozVlastnika
     */
    OperationManager operationManager;
    public ZmenaMajitela() {
        operationManager = new OperationManager();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonZmen = new javax.swing.JButton();
        LabelRodneCislo = new javax.swing.JLabel();
        TFRodneCislo = new javax.swing.JTextField();
        labelState = new javax.swing.JLabel();
        labelSupisneCislo = new javax.swing.JLabel();
        TFsupisneCislo = new javax.swing.JTextField();
        LabelNazovKatastralnehoUzemia = new javax.swing.JLabel();
        TFNazovKatastralnehoUzemia = new javax.swing.JTextField();
        labelRemve = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        buttonZmen.setText("Zmen");
        buttonZmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZmenActionPerformed(evt);
            }
        });

        LabelRodneCislo.setLabelFor(TFRodneCislo);
        LabelRodneCislo.setText("rodne cislo");

        TFRodneCislo.setText("rodne cislo");
        TFRodneCislo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFRodneCisloActionPerformed(evt);
            }
        });

        labelState.setText("XXXX");

        labelSupisneCislo.setText("supisne cislo");

        TFsupisneCislo.setText("supisne cislo");
        TFsupisneCislo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFsupisneCisloActionPerformed(evt);
            }
        });

        LabelNazovKatastralnehoUzemia.setText("nazov katastralneho uzemia");

        TFNazovKatastralnehoUzemia.setText("Nazov Katastralneh oUzemia");
        TFNazovKatastralnehoUzemia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNazovKatastralnehoUzemiaActionPerformed(evt);
            }
        });

        labelRemve.setText("Zmena majitela nehnutelnosti v zadanom kat. uzemi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonZmen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNazovKatastralnehoUzemia)
                            .addComponent(labelSupisneCislo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFNazovKatastralnehoUzemia, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(TFsupisneCislo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelRodneCislo, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(TFRodneCislo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelRemve)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(labelRemve)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFsupisneCislo)
                    .addComponent(labelSupisneCislo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFNazovKatastralnehoUzemia)
                    .addComponent(LabelNazovKatastralnehoUzemia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFRodneCislo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelRodneCislo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(buttonZmen)
                .addGap(18, 18, 18)
                .addComponent(labelState)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TFRodneCisloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFRodneCisloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFRodneCisloActionPerformed

    private void buttonZmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZmenActionPerformed
        String rodneCislo = TFRodneCislo.getText();
        String nazovKatastralnehoUzemia = TFNazovKatastralnehoUzemia.getText();
        int idSupisneCislo = Integer.parseInt(TFsupisneCislo.getText());

        String result= "";
        //String result = operationManager.getOperation15().insertOsoba(rodneCislo,menoPriezvisko,trvalyPobyt);
        labelState.setText(result);
    }//GEN-LAST:event_buttonZmenActionPerformed

    private void TFsupisneCisloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFsupisneCisloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFsupisneCisloActionPerformed

    private void TFNazovKatastralnehoUzemiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNazovKatastralnehoUzemiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNazovKatastralnehoUzemiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelNazovKatastralnehoUzemia;
    private javax.swing.JLabel LabelRodneCislo;
    private javax.swing.JTextField TFNazovKatastralnehoUzemia;
    private javax.swing.JTextField TFRodneCislo;
    private javax.swing.JTextField TFsupisneCislo;
    private javax.swing.JButton buttonZmen;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelRemve;
    private javax.swing.JLabel labelState;
    private javax.swing.JLabel labelSupisneCislo;
    // End of variables declaration//GEN-END:variables
}
