package GUI;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import dataLogic.OperationManager;

/**
 *
 * @author Malbac
 */
public class VlozListVlastnictva extends javax.swing.JPanel {

    /**
     * Creates new form VlozVlastnika
     */
    OperationManager operationManager;
    public VlozListVlastnictva() {
        operationManager = new OperationManager();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVlozOsoba = new javax.swing.JButton();
        LabelCisloListuVlastnictva = new javax.swing.JLabel();
        TFCisloListuVlastnictva = new javax.swing.JTextField();
        TFKatastralneUzemie = new javax.swing.JTextField();
        LabelKatastralneUzemie = new javax.swing.JLabel();
        labelState = new javax.swing.JLabel();

        jButtonVlozOsoba.setText("Vloz");
        jButtonVlozOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVlozOsobaActionPerformed(evt);
            }
        });

        LabelCisloListuVlastnictva.setLabelFor(TFCisloListuVlastnictva);
        LabelCisloListuVlastnictva.setText("Cislo Listu Vlastnictva");

        TFCisloListuVlastnictva.setText("Cislo Listu Vlastnictva");
        TFCisloListuVlastnictva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCisloListuVlastnictvaActionPerformed(evt);
            }
        });

        TFKatastralneUzemie.setText("katastralne uzemie");
        TFKatastralneUzemie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFKatastralneUzemieActionPerformed(evt);
            }
        });

        LabelKatastralneUzemie.setLabelFor(TFKatastralneUzemie);
        LabelKatastralneUzemie.setText("nazov katastralneho uzemie");

        labelState.setText("XXXX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVlozOsoba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelCisloListuVlastnictva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(LabelKatastralneUzemie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFKatastralneUzemie)
                            .addComponent(TFCisloListuVlastnictva, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                    .addComponent(labelState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFKatastralneUzemie, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(LabelKatastralneUzemie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFCisloListuVlastnictva)
                    .addComponent(LabelCisloListuVlastnictva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonVlozOsoba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelState)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TFCisloListuVlastnictvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCisloListuVlastnictvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFCisloListuVlastnictvaActionPerformed

    private void TFKatastralneUzemieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFKatastralneUzemieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFKatastralneUzemieActionPerformed

    private void jButtonVlozOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVlozOsobaActionPerformed
        String nazovKatastralnehoUzemia = TFKatastralneUzemie.getText();
        int idListVlastnictva = Integer.parseInt(TFCisloListuVlastnictva.getText());

        String result = operationManager.getOperation16().insertListVlastnictva(nazovKatastralnehoUzemia, idListVlastnictva);
        labelState.setText(result);
    }//GEN-LAST:event_jButtonVlozOsobaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCisloListuVlastnictva;
    private javax.swing.JLabel LabelKatastralneUzemie;
    private javax.swing.JTextField TFCisloListuVlastnictva;
    private javax.swing.JTextField TFKatastralneUzemie;
    private javax.swing.JButton jButtonVlozOsoba;
    private javax.swing.JLabel labelState;
    // End of variables declaration//GEN-END:variables
}
