package GUI.insertDialog;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import dataLogic.OperationManager;

/**
 *
 * @author Malbac
 */
public class VlozKatastralneUzemie extends javax.swing.JPanel {

    /**
     * Creates new form VlozVlastnika
     */
    OperationManager operationManager;
    public VlozKatastralneUzemie() {
        operationManager = new OperationManager();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVlozKatastralneUzemie = new javax.swing.JButton();
        LabelNazovKatastralnehoUzemia = new javax.swing.JLabel();
        TFNazovKatastralnehoUzemia = new javax.swing.JTextField();
        TFKatastralneUzemie = new javax.swing.JTextField();
        LabelKatastralneUzemie = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LabelIdUradu = new javax.swing.JLabel();
        TFIdUradu = new javax.swing.JTextField();
        labelState = new javax.swing.JLabel();

        jButtonVlozKatastralneUzemie.setText("Vloz");
        jButtonVlozKatastralneUzemie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVlozKatastralneUzemieActionPerformed(evt);
            }
        });

        LabelNazovKatastralnehoUzemia.setLabelFor(TFNazovKatastralnehoUzemia);
        LabelNazovKatastralnehoUzemia.setText("nazov katastralneho uzemia");

        TFNazovKatastralnehoUzemia.setText("Nazov Katastralneh oUzemia");
        TFNazovKatastralnehoUzemia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNazovKatastralnehoUzemiaActionPerformed(evt);
            }
        });

        TFKatastralneUzemie.setText("katastralne uzemie");
        TFKatastralneUzemie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFKatastralneUzemieActionPerformed(evt);
            }
        });

        LabelKatastralneUzemie.setLabelFor(TFKatastralneUzemie);
        LabelKatastralneUzemie.setText("id katastralne uzemie");

        LabelIdUradu.setLabelFor(TFKatastralneUzemie);
        LabelIdUradu.setText("id uradu");

        TFIdUradu.setText("id uradu");
        TFIdUradu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFIdUraduActionPerformed(evt);
            }
        });

        labelState.setText("XXXX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jButtonVlozKatastralneUzemie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelNazovKatastralnehoUzemia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(LabelKatastralneUzemie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFKatastralneUzemie)
                            .addComponent(TFNazovKatastralnehoUzemia, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelIdUradu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFIdUradu, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFIdUradu)
                    .addComponent(LabelIdUradu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFKatastralneUzemie)
                    .addComponent(LabelKatastralneUzemie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFNazovKatastralnehoUzemia, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(LabelNazovKatastralnehoUzemia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButtonVlozKatastralneUzemie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelState)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TFNazovKatastralnehoUzemiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNazovKatastralnehoUzemiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNazovKatastralnehoUzemiaActionPerformed

    private void TFKatastralneUzemieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFKatastralneUzemieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFKatastralneUzemieActionPerformed

    private void TFIdUraduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFIdUraduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFIdUraduActionPerformed

    private void jButtonVlozKatastralneUzemieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVlozKatastralneUzemieActionPerformed
        int idUradu = Integer.parseInt(TFIdUradu.getText());
        int idKatastralnehoUzemia = Integer.parseInt(TFKatastralneUzemie.getText());
        String nazovKatastralnehoUzemia = TFNazovKatastralnehoUzemia.getText();

        String result = operationManager.getOperation21().insertKatastralneUzemie(idUradu,idKatastralnehoUzemia,nazovKatastralnehoUzemia);
        labelState.setText(result);
    }//GEN-LAST:event_jButtonVlozKatastralneUzemieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelIdUradu;
    private javax.swing.JLabel LabelKatastralneUzemie;
    private javax.swing.JLabel LabelNazovKatastralnehoUzemia;
    private javax.swing.JTextField TFIdUradu;
    private javax.swing.JTextField TFKatastralneUzemie;
    private javax.swing.JTextField TFNazovKatastralnehoUzemia;
    private javax.swing.JButton jButtonVlozKatastralneUzemie;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelState;
    // End of variables declaration//GEN-END:variables
}
