package GUI.insertDialog;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import dataLogic.OperationManager;

/**
 *
 * @author Malbac
 */
public class VlozPodiel extends javax.swing.JPanel {

    /**
     * Creates new form VlozVlastnika
     */
    OperationManager operationManager;
    public VlozPodiel() {
        operationManager = new OperationManager();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVlozOsoba = new javax.swing.JButton();
        TFIdPodiel = new javax.swing.JTextField();
        LabelIdPodiel = new javax.swing.JLabel();
        LabelIdSupisneCislo = new javax.swing.JLabel();
        TFSupisneCislo = new javax.swing.JTextField();
        TFRodneCislo = new javax.swing.JTextField();
        labelRodneCislo = new javax.swing.JLabel();
        labelState = new javax.swing.JLabel();
        LabelVelkostPodielu = new javax.swing.JLabel();
        TFVelkostPodielu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        jButtonVlozOsoba.setText("Vloz");
        jButtonVlozOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVlozOsobaActionPerformed(evt);
            }
        });

        TFIdPodiel.setText("id podiel");
        TFIdPodiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFIdPodielActionPerformed(evt);
            }
        });

        LabelIdPodiel.setLabelFor(TFIdPodiel);
        LabelIdPodiel.setText("id podiel");

        LabelIdSupisneCislo.setLabelFor(TFSupisneCislo);
        LabelIdSupisneCislo.setText("rodne cislo");

        TFSupisneCislo.setText("supisne cislo");
        TFSupisneCislo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSupisneCisloActionPerformed(evt);
            }
        });

        TFRodneCislo.setText("rodneCislo");
        TFRodneCislo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFRodneCisloActionPerformed(evt);
            }
        });

        labelRodneCislo.setLabelFor(TFRodneCislo);
        labelRodneCislo.setText("rodne_cislo");

        labelState.setText("XXXX");

        LabelVelkostPodielu.setLabelFor(TFIdPodiel);
        LabelVelkostPodielu.setText("velkost podielu");

        TFVelkostPodielu.setText("velkost podielu");
        TFVelkostPodielu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFVelkostPodieluActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelRodneCislo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFRodneCislo, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                    .addComponent(jButtonVlozOsoba, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(LabelIdSupisneCislo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelIdPodiel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelVelkostPodielu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFVelkostPodielu)
                            .addComponent(TFSupisneCislo)
                            .addComponent(TFIdPodiel, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFRodneCislo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRodneCislo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFSupisneCislo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(LabelIdSupisneCislo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFIdPodiel)
                    .addComponent(LabelIdPodiel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFVelkostPodielu)
                    .addComponent(LabelVelkostPodielu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonVlozOsoba)
                .addGap(18, 18, 18)
                .addComponent(labelState)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TFSupisneCisloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSupisneCisloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSupisneCisloActionPerformed

    private void TFIdPodielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFIdPodielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFIdPodielActionPerformed

    private void TFRodneCisloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFRodneCisloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFRodneCisloActionPerformed

    private void jButtonVlozOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVlozOsobaActionPerformed
        String rodneCislo = TFSupisneCislo.getText();
        String menoPriezvisko = TFRodneCislo.getText();
        String trvalyPobyt = TFIdPodiel.getText();

        String result = operationManager.getOperation15().insertOsoba(rodneCislo,menoPriezvisko,trvalyPobyt);
        labelState.setText(result);
    }//GEN-LAST:event_jButtonVlozOsobaActionPerformed

    private void TFVelkostPodieluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFVelkostPodieluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFVelkostPodieluActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelIdPodiel;
    private javax.swing.JLabel LabelIdSupisneCislo;
    private javax.swing.JLabel LabelVelkostPodielu;
    private javax.swing.JTextField TFIdPodiel;
    private javax.swing.JTextField TFRodneCislo;
    private javax.swing.JTextField TFSupisneCislo;
    private javax.swing.JTextField TFVelkostPodielu;
    private javax.swing.JButton jButtonVlozOsoba;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelRodneCislo;
    private javax.swing.JLabel labelState;
    // End of variables declaration//GEN-END:variables
}
