package GUI.insertDialog;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import data.DataManager;
import dataLogic.OperationManager;

/**
 *
 * @author Malbac
 */
public class VlozKatastralnyUrad extends javax.swing.JPanel {

    /**
     * Creates new form VlozVlastnika
     */
    OperationManager operationManager;
    public VlozKatastralnyUrad(DataManager dataManager) {
        operationManager = new OperationManager(dataManager);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVlozOsoba = new javax.swing.JButton();
        TFIdKatastralnyUrad = new javax.swing.JTextField();
        LabelKatastralnyUrad = new javax.swing.JLabel();
        labelState = new javax.swing.JLabel();

        jButtonVlozOsoba.setText("Vloz");
        jButtonVlozOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVlozOsobaActionPerformed(evt);
            }
        });

        TFIdKatastralnyUrad.setText("katastralny urad");
        TFIdKatastralnyUrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFIdKatastralnyUradActionPerformed(evt);
            }
        });

        LabelKatastralnyUrad.setLabelFor(TFIdKatastralnyUrad);
        LabelKatastralnyUrad.setText("id katastraneho uradu");

        labelState.setText("XXXX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVlozOsoba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelKatastralnyUrad, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(TFIdKatastralnyUrad, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFIdKatastralnyUrad, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(LabelKatastralnyUrad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButtonVlozOsoba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelState)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TFIdKatastralnyUradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFIdKatastralnyUradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFIdKatastralnyUradActionPerformed

    private void jButtonVlozOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVlozOsobaActionPerformed
        int idUradu = Integer.parseInt(TFIdKatastralnyUrad.getText());

        String result = operationManager.getOperationKatastralnyUrad().vlozKatastralnyUrad(idUradu);
        labelState.setText(result);
    }//GEN-LAST:event_jButtonVlozOsobaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelKatastralnyUrad;
    private javax.swing.JTextField TFIdKatastralnyUrad;
    private javax.swing.JButton jButtonVlozOsoba;
    private javax.swing.JLabel labelState;
    // End of variables declaration//GEN-END:variables
}
