package GUI.insertDialog;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import dataLogic.OperationManager;

/**
 *
 * @author Malbac
 */
public class VlozVlastnika extends javax.swing.JPanel {

    /**
     * Creates new form VlozVlastnika
     */
    OperationManager operationManager;
    public VlozVlastnika() {
        operationManager = new OperationManager();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVlozOsoba = new javax.swing.JButton();
        TFTrvalyPobyt = new javax.swing.JTextField();
        LabeltrvalyPobyt = new javax.swing.JLabel();
        LabelRodneCislo = new javax.swing.JLabel();
        TFRodneCislo = new javax.swing.JTextField();
        TFMenoAPriezvisko = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelState = new javax.swing.JLabel();

        jButtonVlozOsoba.setText("Vloz");
        jButtonVlozOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVlozOsobaActionPerformed(evt);
            }
        });

        TFTrvalyPobyt.setText("trvaly pobyt");
        TFTrvalyPobyt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTrvalyPobytActionPerformed(evt);
            }
        });

        LabeltrvalyPobyt.setLabelFor(TFTrvalyPobyt);
        LabeltrvalyPobyt.setText("trvaly pobyt");

        LabelRodneCislo.setLabelFor(TFRodneCislo);
        LabelRodneCislo.setText("rodne cislo");

        TFRodneCislo.setText("rodne cislo");
        TFRodneCislo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFRodneCisloActionPerformed(evt);
            }
        });

        TFMenoAPriezvisko.setText("meno a priezvisko");
        TFMenoAPriezvisko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFMenoAPriezviskoActionPerformed(evt);
            }
        });

        jLabel1.setLabelFor(TFMenoAPriezvisko);
        jLabel1.setText("meno a priezvisko");

        labelState.setText("XXXX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVlozOsoba, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFMenoAPriezvisko, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(LabelRodneCislo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabeltrvalyPobyt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFRodneCislo)
                            .addComponent(TFTrvalyPobyt, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                    .addComponent(labelState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFMenoAPriezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFRodneCislo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(LabelRodneCislo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFTrvalyPobyt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(LabeltrvalyPobyt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVlozOsoba)
                .addGap(18, 18, 18)
                .addComponent(labelState)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TFRodneCisloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFRodneCisloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFRodneCisloActionPerformed

    private void TFTrvalyPobytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTrvalyPobytActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTrvalyPobytActionPerformed

    private void TFMenoAPriezviskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFMenoAPriezviskoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFMenoAPriezviskoActionPerformed

    private void jButtonVlozOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVlozOsobaActionPerformed
        String rodneCislo = TFRodneCislo.getText();
        String menoPriezvisko = TFMenoAPriezvisko.getText();
        String trvalyPobyt = TFTrvalyPobyt.getText();

        String result = operationManager.getOperation15().insertOsoba(rodneCislo,menoPriezvisko,trvalyPobyt);
        labelState.setText(result);
    }//GEN-LAST:event_jButtonVlozOsobaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelRodneCislo;
    private javax.swing.JLabel LabeltrvalyPobyt;
    private javax.swing.JTextField TFMenoAPriezvisko;
    private javax.swing.JTextField TFRodneCislo;
    private javax.swing.JTextField TFTrvalyPobyt;
    private javax.swing.JButton jButtonVlozOsoba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelState;
    // End of variables declaration//GEN-END:variables
}
