package GUI.test;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import GUI.insertDialog.*;
import data.DataManager;
import dataLogic.OperationManager;
import generatorOperaci.InsertDataGenerator;

/**
 *
 * @author Malbac
 */
public class GenerateData extends javax.swing.JPanel {

    /**
     * Creates new form VlozVlastnika
     */
    DataManager dataManager;
    OperationManager operationManager;
    public GenerateData(DataManager dataManager) {
        this.dataManager = dataManager;
        operationManager = new OperationManager(dataManager);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TFKatastralnyUrad = new javax.swing.JTextField();
        SliderKatastralnyUrad = new javax.swing.JSlider();
        labelOpakovania = new javax.swing.JLabel();
        labelOpakovania1 = new javax.swing.JLabel();
        TFKatastralneUzemie = new javax.swing.JTextField();
        SliderKatastralneUzemie = new javax.swing.JSlider();
        labelOpakovania2 = new javax.swing.JLabel();
        TFListVlastnictva = new javax.swing.JTextField();
        SliderListVlastnictva = new javax.swing.JSlider();
        labelOpakovania3 = new javax.swing.JLabel();
        TFNehnutelnost = new javax.swing.JTextField();
        SliderNehnutelnst = new javax.swing.JSlider();
        labelOpakovania4 = new javax.swing.JLabel();
        TFPodiel = new javax.swing.JTextField();
        SliderPodiel = new javax.swing.JSlider();
        labelOpakovania5 = new javax.swing.JLabel();
        TFOsoba = new javax.swing.JTextField();
        SliderOsoba = new javax.swing.JSlider();
        labelState = new javax.swing.JLabel();
        generateData = new javax.swing.JButton();

        TFKatastralnyUrad.setText("0");

        SliderKatastralnyUrad.setMaximum(1000);
        SliderKatastralnyUrad.setValue(0);
        SliderKatastralnyUrad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderKatastralnyUradStateChanged(evt);
            }
        });

        labelOpakovania.setText("KatastralnyUrad");

        labelOpakovania1.setText("Katastralne Uzemie");

        TFKatastralneUzemie.setText("0");

        SliderKatastralneUzemie.setMaximum(1000);
        SliderKatastralneUzemie.setValue(0);
        SliderKatastralneUzemie.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderKatastralneUzemieStateChanged(evt);
            }
        });

        labelOpakovania2.setText("List vlastnictvva");

        TFListVlastnictva.setText("0");

        SliderListVlastnictva.setMaximum(1000);
        SliderListVlastnictva.setValue(0);
        SliderListVlastnictva.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderListVlastnictvaStateChanged(evt);
            }
        });

        labelOpakovania3.setText("nehnutelnost");

        TFNehnutelnost.setText("0");

        SliderNehnutelnst.setMaximum(1000);
        SliderNehnutelnst.setValue(0);
        SliderNehnutelnst.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderNehnutelnstStateChanged(evt);
            }
        });

        labelOpakovania4.setText("podiel");

        TFPodiel.setText("0");

        SliderPodiel.setMaximum(1000);
        SliderPodiel.setValue(0);
        SliderPodiel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderPodielStateChanged(evt);
            }
        });

        labelOpakovania5.setText("osoba");

        TFOsoba.setText("0");

        SliderOsoba.setMaximum(1000);
        SliderOsoba.setValue(0);
        SliderOsoba.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderOsobaStateChanged(evt);
            }
        });

        labelState.setText("XXXX");

        generateData.setText("GenerateData");
        generateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelOpakovania2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TFListVlastnictva, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SliderListVlastnictva, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelOpakovania3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFNehnutelnost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SliderNehnutelnst, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelOpakovania, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelOpakovania1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(TFKatastralneUzemie)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SliderKatastralneUzemie, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TFKatastralnyUrad, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SliderKatastralnyUrad, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelOpakovania5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelOpakovania4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFOsoba)
                                    .addComponent(TFPodiel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SliderPodiel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SliderOsoba, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(labelState, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateData))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderKatastralnyUrad, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(TFKatastralnyUrad)
                    .addComponent(labelOpakovania, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderKatastralneUzemie, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(TFKatastralneUzemie)
                    .addComponent(labelOpakovania1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderListVlastnictva, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(TFListVlastnictva)
                    .addComponent(labelOpakovania2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderNehnutelnst, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(TFNehnutelnost)
                    .addComponent(labelOpakovania3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderPodiel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(TFPodiel)
                    .addComponent(labelOpakovania4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderOsoba, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(TFOsoba)
                    .addComponent(labelOpakovania5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(generateData)
                .addGap(11, 11, 11)
                .addComponent(labelState)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateDataActionPerformed
        InsertDataGenerator insertDataGenerator = new InsertDataGenerator(dataManager);
        int katUrad = Integer.parseInt(TFKatastralnyUrad.getText());
        int katUzemie= Integer.parseInt(TFKatastralneUzemie.getText());
        int listVlastnictva= Integer.parseInt(TFListVlastnictva.getText());
        int nehnutelnost= Integer.parseInt(TFNehnutelnost.getText());
        int podiel= Integer.parseInt(TFPodiel.getText());
        int osoba= Integer.parseInt(TFOsoba.getText());
        insertDataGenerator.naplnData(katUrad, katUzemie, listVlastnictva, nehnutelnost, podiel, osoba);
    }//GEN-LAST:event_generateDataActionPerformed

    private void SliderKatastralnyUradStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderKatastralnyUradStateChanged
        TFKatastralnyUrad.setText(SliderKatastralnyUrad.getValue()+"");
    }//GEN-LAST:event_SliderKatastralnyUradStateChanged

    private void SliderKatastralneUzemieStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderKatastralneUzemieStateChanged
        TFKatastralneUzemie.setText(SliderKatastralneUzemie.getValue()+"");
    }//GEN-LAST:event_SliderKatastralneUzemieStateChanged

    private void SliderListVlastnictvaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderListVlastnictvaStateChanged
        TFListVlastnictva.setText(SliderListVlastnictva.getValue()+"");
    }//GEN-LAST:event_SliderListVlastnictvaStateChanged

    private void SliderNehnutelnstStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderNehnutelnstStateChanged
        TFNehnutelnost.setText(SliderNehnutelnst.getValue()+"");
    }//GEN-LAST:event_SliderNehnutelnstStateChanged

    private void SliderPodielStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderPodielStateChanged
        TFPodiel.setText(SliderPodiel.getValue()+"");
    }//GEN-LAST:event_SliderPodielStateChanged

    private void SliderOsobaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderOsobaStateChanged
        TFOsoba.setText(SliderOsoba.getValue()+"");
    }//GEN-LAST:event_SliderOsobaStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider SliderKatastralneUzemie;
    private javax.swing.JSlider SliderKatastralnyUrad;
    private javax.swing.JSlider SliderListVlastnictva;
    private javax.swing.JSlider SliderNehnutelnst;
    private javax.swing.JSlider SliderOsoba;
    private javax.swing.JSlider SliderPodiel;
    private javax.swing.JTextField TFKatastralneUzemie;
    private javax.swing.JTextField TFKatastralnyUrad;
    private javax.swing.JTextField TFListVlastnictva;
    private javax.swing.JTextField TFNehnutelnost;
    private javax.swing.JTextField TFOsoba;
    private javax.swing.JTextField TFPodiel;
    private javax.swing.JButton generateData;
    private javax.swing.JLabel labelOpakovania;
    private javax.swing.JLabel labelOpakovania1;
    private javax.swing.JLabel labelOpakovania2;
    private javax.swing.JLabel labelOpakovania3;
    private javax.swing.JLabel labelOpakovania4;
    private javax.swing.JLabel labelOpakovania5;
    private javax.swing.JLabel labelState;
    // End of variables declaration//GEN-END:variables
}
